### ISSUE TITLE
Create the notifications database using Room.

### ISSUE THREAD

**Issue by steebe** [collinpreston/Mayti#2]
**Overview**
Create a feature set that allows for users to receive notifications about items in their watchlists.

**Done When**
1. There are entities created to bootstrap tables that support and store notification information
2. A service has been developed to poll for relevant db updates for notification criteria
3. Upon changes being detected, an alert has been pushed to the user 

**Notification Criteria**
1. In Progress..

**Comment by collinpreston** [comment]
This is dependent on the notifications engine story.

**Comment by collinpreston** [comment]
Need to consider how we'll be tracking which alert methods the user is subscribed to.  There is also a need to specify the specifics of those notification subscriptions (such as percent change they want to be alerted about).
