### ISSUE TITLE
Watch list card UI updates.

### ISSUE THREAD

**Issue by steebe** [collinpreston/Mayti#4]
**Overview**
The stock cards need to be developed more to improve the look & feel.

**Done When**
For cards within watch lists:
1. Labels need to be added to the data within a stock card
2. Micro charts on stock information should be on stock cards
3.

**Comment by collinpreston** [comment]
Chart times should only be 1d, 5d, 3m, 1y

**Comment by collinpreston** [comment]
Need to add Bid and Ask prices.  Also need to add removal icon at top right corner.

**Comment by collinpreston** [comment]
This is complete.  Unable to add bid and ask prices due to data availability.  Only need to add "update time" at bottom in small, grey, font.
